exponent = ""
modulus_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
redc_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
signature_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
sod_hash = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
