[workspace]
members = [
    "passport_verifier",
    "data_integrity",
    "disclosure",
    "prepare_link",
    "show_link",
    "openac_core",
    "passport_adapter",
    "openac_show",
    "device_binding",
    "sdjwt_adapter",
]
default-member = "passport_verifier"
